create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null default 'NovaPay User',avatar_url text,account_number text unique not null,created_at timestamptz not null default now());
create table if not exists public.wallets(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references public.profiles(id) on delete cascade,currency text not null default 'USD',balance numeric(18,2) not null default 0 check(balance>=0),pending numeric(18,2) not null default 0 check(pending>=0),created_at timestamptz not null default now());
create table if not exists public.transactions(id uuid primary key default gen_random_uuid(),wallet_id uuid not null references public.wallets(id) on delete cascade,type text not null check(type in('send','receive','deposit','withdrawal')),amount numeric(18,2) not null check(amount>0),currency text not null default 'USD',status text not null default 'success' check(status in('pending','success','failed')),counterparty_name text,counterparty_account text,reference text not null unique,idempotency_key text unique,note text,created_at timestamptz not null default now());
create table if not exists public.beneficiaries(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,name text not null,account_number text not null,bank_name text,created_at timestamptz not null default now());
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,title text not null,body text not null,read boolean not null default false,created_at timestamptz not null default now());
alter table public.profiles enable row level security;alter table public.wallets enable row level security;alter table public.transactions enable row level security;alter table public.beneficiaries enable row level security;alter table public.notifications enable row level security;
drop policy if exists profiles_select_own on public.profiles;create policy profiles_select_own on public.profiles for select using(auth.uid()=id);
drop policy if exists profiles_insert_own on public.profiles;create policy profiles_insert_own on public.profiles for insert with check(auth.uid()=id);
drop policy if exists profiles_update_own on public.profiles;create policy profiles_update_own on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists wallets_select_own on public.wallets;create policy wallets_select_own on public.wallets for select using(auth.uid()=user_id);
drop policy if exists wallets_insert_own on public.wallets;create policy wallets_insert_own on public.wallets for insert with check(auth.uid()=user_id);
drop policy if exists transactions_select_own on public.transactions;create policy transactions_select_own on public.transactions for select using(exists(select 1 from public.wallets w where w.id=wallet_id and w.user_id=auth.uid()));
drop policy if exists beneficiaries_all_own on public.beneficiaries;create policy beneficiaries_all_own on public.beneficiaries for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists notifications_all_own on public.notifications;create policy notifications_all_own on public.notifications for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create or replace function public.transfer_money(p_recipient_account text,p_amount numeric,p_note text,p_idempotency_key text) returns jsonb language plpgsql security definer set search_path=public as $$
declare sw public.wallets%rowtype;rw public.wallets%rowtype;sp public.profiles%rowtype;rp public.profiles%rowtype;ref text;existing_id uuid;
begin
if auth.uid() is null then raise exception 'Not authenticated';end if;if p_amount is null or p_amount<=0 then raise exception 'Amount must be greater than zero';end if;
select * into sp from profiles where id=auth.uid();select * into sw from wallets where user_id=auth.uid() for update;if sw.id is null then raise exception 'Sender wallet not found';end if;
select id into existing_id from transactions where idempotency_key=p_idempotency_key limit 1;if existing_id is not null then return jsonb_build_object('transaction_id',existing_id,'duplicate',true);end if;
select * into rp from profiles where account_number=p_recipient_account;if rp.id is null then raise exception 'Recipient account not found';end if;if rp.id=auth.uid() then raise exception 'You cannot transfer to your own account';end if;
select * into rw from wallets where user_id=rp.id for update;if rw.id is null then raise exception 'Recipient wallet not found';end if;if sw.balance<p_amount then raise exception 'Insufficient available balance';end if;
ref:='TXN-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12));update wallets set balance=balance-p_amount where id=sw.id;update wallets set balance=balance+p_amount where id=rw.id;
insert into transactions(wallet_id,type,amount,currency,status,counterparty_name,counterparty_account,reference,idempotency_key,note) values(sw.id,'send',p_amount,sw.currency,'success',rp.full_name,rp.account_number,ref,p_idempotency_key,p_note);
insert into transactions(wallet_id,type,amount,currency,status,counterparty_name,counterparty_account,reference,note) values(rw.id,'receive',p_amount,rw.currency,'success',sp.full_name,sp.account_number,ref||'-R',p_note);
insert into notifications(user_id,title,body) values(auth.uid(),'Transfer sent','You sent '||p_amount||' '||sw.currency||' to '||rp.full_name||'.'),(rp.id,'Money received','You received '||p_amount||' '||rw.currency||' from '||sp.full_name||'.');
return jsonb_build_object('reference',ref,'amount',p_amount,'status','success');end;$$;
revoke all on function public.transfer_money(text,numeric,text,text) from public;grant execute on function public.transfer_money(text,numeric,text,text) to authenticated;